config/routes.rb
Rails.application.routes.draw do

  root 'users#show'

  devise_for :users
  get 'welcome/about'

  get 'welcome/index'
  resources :items
  resources :users do
    resources :items, only: [:new, :create, :destroy]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = "Item was saved"
      redirect_to current_user
    else
      flash[:error] = "There was an error saving the item."
      render :create
    end
  end

  def destroy

    @item = current_user.items.find(params[:id])

    if @item.destroy
      flash[:notice] = "Completed"
    else
      flash[:alert] = "Item couldn't be completed"
    end

    respond_to do |format|
      format.html
      format.js
   end

  end


  private

  def item_params
    params.require(:item).permit(:name, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = current_user
    @item = Item.new
    @items = @user.items
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div class="col-md-8">
  <%= form_for [@user,@item] do |f| %>

    <div class="form-group">
      <%= f.label :name  %>
      <%= f.text_field :name %>
    </div>


    <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/items/_item.html.erb
<% @items.each do |item| %>

  <div class="container" id="item-<%= item.id %>">
    <div class="row">
      <div class="col-sm">
        <h4><%= item.name %></h4>
        <div class="col-sm">
          <%= link_to "", item, method: :delete, class: 'glyphicon glyphicon-ok', remote: true %>
        </div>
          <div class="col-sm">
            <%= distance_of_time_in_words(Time.now, item.created_at + 7.days ) %> left <br>
          </div>
        </div>
      </div>
  </div>

<% end %>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $("#item-<%= @item.id %>").hide();
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>
<%= render partial: 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">

    <%= yield %>
  </div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<% if user_signed_in? %>
  Signed in as: <strong><%= current_user.email %></strong> |
  <ul class="nav nav-tabs">
    <li><%= link_to "Home", welcome_index_path %></li>
    <li><%= link_to "About", welcome_about_path %></li>
    <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <li><%= link_to 'Add Item', new_user_item_path(@user) %></li>
  </ul>
  <%= render partial: 'items/item' %>
<% else %>
  <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
  <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/welcome/about.html.erb
<h1>About Blocitoff</h1>
<p>Blocitoff is an application that allows users to create self-destructing to-do lists</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocitoff</h1>